"""create students, subjects, junction tables

Revision ID: 7dbf0ad77b45
Revises: 1eecd9dbc6fc
Create Date: 2026-09-17 18:34:36.729544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dbf0ad77b45'
down_revision: Union[str, Sequence[str], None] = '1eecd9dbc6fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('junction_subject_id_fkey'), 'junction', type_='foreignkey')
    op.drop_constraint(op.f('junction_student_id_fkey'), 'junction', type_='foreignkey')
    op.create_foreign_key(None, 'junction', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'junction', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'junction', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'junction', type_='foreignkey')
    op.create_foreign_key(op.f('junction_student_id_fkey'), 'junction', 'students', ['student_id'], ['id'])
    op.create_foreign_key(op.f('junction_subject_id_fkey'), 'junction', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###
